accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('signup',views.signup,name = 'signup'),
	path('profile/edit',views.profile_edit,name = 'profile_edit'),
	path('profile/<str:slug>',views.profile,name = 'profile'),
	
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/', include('accounts.urls', namespace = 'accounts')),
	path('admin/', admin.site.urls),
    path('', include('room.urls',namespace = 'room')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

room/urls.py
from django.urls import path
from . import views

app_name = "room"

urlpatterns = [
	path('',views.room_list, name = 'room_list'),
	path('create_room',views.create_room, name = 'create_room'),
	path('category=<slug:category>',views.searchin_by_category,name = 'searchin_by_category'),
	path('<str:slug>',views.room_detail, name = 'room_detail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	num = models.CharField(max_length=50)
	about = models.TextField(null=True,blank=True)
	slug = models.SlugField(blank=True,null=True)

	def save(self,*args,**kwargs):
		self.slug = slugify(self.user.username)
		super(Profile,self).save(*args,**kwargs)


	def __str__(self):
		return str(self.user)




@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

room/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify



class Room(models.Model):
	owner = models.ForeignKey(User,on_delete = models.SET_NULL,null=True)
	title = models.CharField(max_length=50)
	description = models.TextField()
	created = models.DateField(auto_now_add=True, null=True,blank=True)
	modify = models.DateField(auto_now=True)
	participants = models.ManyToManyField(User,related_name='participants', blank=True)
	category = models.ForeignKey('Category', on_delete = models.SET_NULL, null=True)
	slug = models.SlugField(blank=True,null=True)

	def save(self,*args,**kwargs):
		self.slug = slugify(self.title)
		super(Room,self).save(*args,**kwargs)



	class Meta:
		ordering = ['-modify']

	def __str__(self):
		return self.title

class Category(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

class Comment(models.Model):
	user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
	body = models.CharField(max_length=150)
	room = models.ForeignKey(Room,on_delete=models.SET_NULL,null=True)

	def __str__(self):
		return self.body[0:50]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SingUpForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']
	
	

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['num','about']

room/forms.py
from django import forms
from .models import Room,Comment


class RoomForm(forms.ModelForm):
	class Meta:
		model = Room
		fields = '__all__'
		exclude = ('owner','slug')

		
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ["body"]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import SingUpForm, UserForm, ProfileForm
from django.contrib.auth import authenticate, login
from .models import Profile
from django.urls import reverse
from django.contrib.auth.models import User
from room.models import Room,Category,Comment
from django.db.models import Count
from django.contrib import messages

# Create your views here.

def signup(request):
	if request.method == 'POST':
		form = SingUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username = username , password = password)
			login(request,user)
			return redirect('/')
		else:
			messages.error(request, 'An error occurred during registration')
	else:
		form = SingUpForm()
	context = {
			'form':form,
	}
	return render(request,'registration/singup.html',context)


def profile(request, slug):
	profile = Profile.objects.get(slug = slug)
	rooms = Room.objects.filter(owner = profile.id)
	category = Category.objects.annotate(num_items=Count('room'))
	room_messages = Comment.objects.all().order_by('-id')[:5]
	context = {
				'profile': profile,
				'rooms':rooms,
				'category':category,
				'room_messages':room_messages
	}
	return render(request,'accounts/profile.html',context)

def profile_edit(request):
	profile = Profile.objects.get(user = request.user)
	if request.method == "POST":
		userform = UserForm(request.POST,instance = request.user)
		profileform = ProfileForm(request.POST,request.FILES,instance = profile)
		if userform.is_valid() and profileform.is_valid():
			userform.save()
			myprofileform = profileform.save(commit = False)
			myprofileform.user = request.user
			myprofileform.save()
			return redirect('/')
	else:
		userform = UserForm(instance = request.user)
		profileform = ProfileForm(instance = profile)
	context = {
				'userform':userform,
				'profileform':profileform,
	}
	return render(request,'accounts/profileedit.html',context)

room/views.py
from django.shortcuts import render
from .models import Room, Category, Comment
from django.db.models import Count
from .forms import RoomForm, CommentForm
from django.core.paginator import Paginator
from django.db.models import Q



def room_list(request):
	room_list = Room.objects.all()
	search_query = request.GET.get('q')
	if search_query:
		room_list = room_list.filter(
			Q(title__icontains = search_query)|
			Q(description__icontains = search_query)
			)
	paginator = Paginator(room_list, 4)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	category = Category.objects.annotate(num_items=Count('room'))
	x = category.count()
	y = room_list.count()
	room_messages = Comment.objects.all().order_by('-id')[:5]
	context = {
		'room_list':page_obj,
		'category':category,
		'x':x,
		'room_messages':room_messages,
		'y':y
	}
	return render(request,'room/index.html',context)

def room_detail(request,slug):
	room_detail = Room.objects.get(slug = slug)
	participants = room_detail.participants.all()
	comment = reversed(Comment.objects.filter(room = room_detail))
	form = CommentForm()
	if request.method == 'POST':
		owner = request.user
		body = request.POST.get('body')
		rom = room_detail
		Comment.objects.create(user = request.user,body = body,room = rom)
		room_detail.participants.add(request.user)
	context = {
			'room_detail':room_detail,
			'comment':comment,
			'form':form,
			'participants':participants
	}
	return render(request,'room/roomdetail.html',context)

def create_room(request):
	category = Category.objects.all()
	form = RoomForm()

	if request.method =='POST':
		topic_name = request.POST.get('topic')
		topic, created = Category.objects.get_or_create(name=topic_name)
		title = request.POST.get('title')
		description = request.POST.get('description')
		Room.objects.create(owner = request.user,title = title,description=description, category = topic )
		

	context = {
			'form':form,
			'category': category
	}
	return render(request,'room/create-room.html',context)

def searchin_by_category(request,category):
	room_by_category = Room.objects.filter(category__name=category)
	context = {
		'room_list':room_by_category,
		}
	return render(request,'room/index.html',context)

accounts/templates/accounts/profile.html
{% extends "base.html" %}

    <!-- header-start -->
{% block body %}
 <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      <div class="topics">
        <div class="topics__header">
          <h2>Browse Topics</h2>
        </div>
        <ul class="topics__list">
          <li>
            <a href="/" class="active">All <span>{{category.count}}</span></a>
          </li>
          {% for cat in category %}
                    <li>
                      <a href="/">{{cat}} <span>{{cat.num_items}}</span></a>
                    </li>
            {% endfor %}
         
        </ul>
      </div>
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="https://randomuser.me/api/portraits/men/11.jpg" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{profile.user.username}}</h3>
                {% if request.user == profile.user %}
                    <a href="{% url 'accounts:profile_edit' %}" class="btn btn--main btn--pill">Edit Profile</a>
                {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{profile.about}}
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{profile.user.username}}</a>
            </h2>
          </div>
        </div>
        {% for room in rooms %}
            <div class="roomListRoom">
              <div class="roomListRoom__header">
                <a href="profile.html" class="roomListRoom__author">
                  <div class="avatar avatar--small active">
                    <img src="https://randomuser.me/api/portraits/men/11.jpg" />
                  </div>
                  <span>{{room.owner}}</span>
                </a>
                <div class="roomListRoom__actions">
                  <span>{{room.modify|date:"d b Y"}}</span>

                </div>
              </div>
              <div class="roomListRoom__content">
                <a href="{% url 'room:room_detail' room.slug %}">{{room}}</a>
                <p>
                  {{room.description|truncatewords:22}}
                </p>
              </div>
              <div class="roomListRoom__meta">
                <a class="roomListRoom__joined">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>user-group</title>
                    <path
                      d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                    </path>
                    <path
                      d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                    </path>
                    <path
                      d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                    </path>
                    <path
                      d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                    </path>
                  </svg>
                  5.3k Joined
                </a>
                <p class="roomListRoom__topic">{{room.category}}</p>
              </div>
            </div>
        {% endfor %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      <div class="activities">
        <div class="activities__header">
          <h2>Recent Activities</h2>
        </div>
        {% for message in room_messages %}
            
          

              <div class="activities__box">
                <div class="activities__boxHeader roomListRoom__header">
                  <a href="{% url 'accounts:profile' message.user %}" class="roomListRoom__author">
                    <div class="avatar avatar--small">
                      <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                    </div>
                    <p>
                      @{{message.user}}
                    </p>
                  </a>
                  <div class="roomListRoom__actions">
                    {% if request.user == message.user %}
                      
                    
                      <a href="#">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                          ></path>
                        </svg>
                      </a>

                    {% endif %}
                  </div>
                </div>
                <div class="activities__boxContent">
                  <p>replied to post “<a href="{% url 'room:room_detail' message.room.slug %}">{{message.room}}!</a>”</p>
                  <div class="activities__boxRoomContent">
                    {{message}}
                  </div>
                </div>
              </div>

          {% endfor %}
      </div>
      <!-- Activities End -->
    </div>
  </main>
    
{% endblock body %}

<div class="submit_btn">
    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
</div>

room/templates/room/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
		<main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        <div class="topics">
          <div class="topics__header">
            <h2>Browse Topics</h2>
          </div>
          <ul class="topics__list">
            <li>
              <a href="/" class="active">All <span>{{x}}</span></a>
            </li>
            {% for cat in category %}
		            <li>
		              <a href="{% url 'room:searchin_by_category' cat %}">{{cat}} <span>{{cat.num_items}}</span></a>
		            </li>
		    {% endfor %}
          </ul>
          
        </div>
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form  class="header__search" >
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{y}} Rooms available</p>
            </div>
            {% if request.user.is_authenticated %}
                <a class="btn btn--main" href="{% url 'room:create_room' %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>add</title>
                    <path
                      d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                    ></path>
                  </svg>
                  Create Room
                </a>

            {% endif %}
          </div>

          {% for rom in room_list %}
          	
		          <div class="roomListRoom">
		            <div class="roomListRoom__header">
		              <a href="{% url 'accounts:profile' rom.owner %}" class="roomListRoom__author">
		                <div class="avatar avatar--small">
		                  <img src="https://randomuser.me/api/portraits/women/11.jpg" />
		                </div>
		                <span>@{{rom.owner}}</span>
		              </a>
		              <div class="roomListRoom__actions">
		                <span>{{rom.modify|date:"d b Y"}}</span>
		              </div>
		            </div>
		            <div class="roomListRoom__content">
		              <a href="{% url 'room:room_detail' rom.slug %}">{{rom}}</a>
		              <p>
		                {{rom.description|truncatewords:20}}.
		              </p>
		            </div>
		            <div class="roomListRoom__meta">
		              <a href="{% url 'room:room_detail' rom.slug %}" class="roomListRoom__joined">
		                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
		                  <title>user-group</title>
		                  <path
		                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
		                  ></path>
		                  <path
		                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
		                  ></path>
		                  <path
		                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
		                  ></path>
		                  <path
		                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
		                  ></path>
		                </svg>
		                {{rom.participants.count}} Joined
		              </a>
		              <p class="roomListRoom__topic">{{rom.category}}</p>
		            </div>
		          </div>
		          {% endfor %}
              {% if room_list.has_other_pages %}
                  <div class="centeeer">
                      <div class="pagination">
                          {% if room_list.has_previous %}
                            <a href="?page={{room_list.previous_page_number}}">&laquo;</a>
                          {% endif %}

                          {% for i in room_list.paginator.page_range %}
                              <a href="?page={{i}}">{{i}}</a>
                          {% endfor %}
                            
                    
                          {% if room_list.has_next %}
                            <a href="?page={{room_list.next_page_number}}">&raquo;</a>
                          {% endif %}

                      </div>
                    </div>
              {% endif %}
		        </div>
        
        <!-- Room List End -->

        <!-- Activities Start -->
        <div class="activities">
          <div class="activities__header">
            <h2>Recent Activities</h2>
          </div>

          {% for message in room_messages %}
            
          

              <div class="activities__box">
                <div class="activities__boxHeader roomListRoom__header">
                  <a href="{% url 'accounts:profile' message.user %}" class="roomListRoom__author">
                    <div class="avatar avatar--small">
                      <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                    </div>
                    <p>
                      @{{message.user}}
                    </p>
                  </a>
                  <div class="roomListRoom__actions">
                    {% if request.user == message.user %}
                      
                    
                      <a href="#">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                          ></path>
                        </svg>
                      </a>

                    {% endif %}
                  </div>
                </div>
                <div class="activities__boxContent">
                  <p>replied to post “<a href="{% url 'room:room_detail' message.room.slug %}">{{message.room}}!</a>”</p>
                  <div class="activities__boxRoomContent">
                    {{message}}
                  </div>
                </div>
              </div>

          {% endfor %}
        </div>
        <!-- Activities End -->
      </div>
    </main>
{% endblock body %}

room/templates/room/roomdetail.html
{% extends "base.html" %}
{% block body %}
	<main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'room:room_list' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>
            {% if request.user == room_detail.owner %}
              
            
                <div class="room__topRight">
                  <a href="#">
                    <svg
                      enable-background="new 0 0 24 24"
                      height="32"
                      viewBox="0 0 24 24"
                      width="32"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <title>edit</title>
                      <g>
                        <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                      </g>
                      <g>
                        <g>
                          <path
                            d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                          />
                        </g>
                        <g>
                          <path
                            d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                          />
                        </g>
                      </g>
                    </svg>
                  </a>
                  <a href="#">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
            {% endif %}
            <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
            data-edit-url="profile.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>ellipsis-horizontal</title>
              <path
                d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
            </svg>
          </button> -->
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{room_detail.title}}</h3>
                <span>{{room_detail.modify|date:"d b Y"}}</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="#" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                  </div>
                  <span>{{room_detail.owner}}</span>
                </a>
              </div>
              <div class="room__details">
                {{room_detail.description}}
              </div>
              <span class="room__topics">{{room_detail.category}}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for comm in comment %}
                  
                
                  <div class="thread">
                    <div class="thread__top">
                      <div class="thread__author">
                        <a href="{% url 'accounts:profile' comm.user %}" class="thread__authorInfo">
                          <div class="avatar avatar--small">
                            <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                          </div>
                          <span>@{{comm.user}}</span>
                        </a>
                        
                      </div>
                      {% if request.user == comm.user %}
                        
                      
                          <div class="thread__delete">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                              <title>remove</title>
                              <path
                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                              ></path>
                            </svg>
                          </div>
                      {% endif %}
                    </div>
                    <div class="thread__details">
                      {{comm.body}}
                    </div>
                  </div>

                {% endfor %}

              </div>
            </div>
          </div>
          <div class="room__message">
            {% if request.user.is_authenticated %}
              
            
              <form method="POST">
                {% csrf_token %}
                  {{form.body}}
              </form>
            {% endif %}
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
          <div class="participants__list scroll">
            {% for parti in participants %}
              <a href="{% url 'accounts:profile' parti.username %}" class="participant">
                <div class="avatar avatar--medium">
                  <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                </div>
                <p>
                  {{parti.username}}
                </p>
              </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
{% endblock body %}